In [1]:
import torch

In [2]:
torch.__version__

'1.5.1'

In [10]:
import numpy as np
lst = [1, 2, 3, 4]
arr = np.array(lst)

In [6]:
arr

array([1, 2, 3, 4])

In [12]:
print(arr.shape)

(4,)


In [16]:
arr.dtype

dtype('int64')

In [17]:
tensors = torch.from_numpy(arr)
tensors

tensor([1, 2, 3, 4])

In [20]:
tensors.dtype

torch.int64

In [21]:
tensors[:2]

tensor([1, 2])

In [22]:
tensors[2]

tensor(3)

In [23]:
tensors[1:4]

tensor([2, 3, 4])

In [24]:
tensors[2] = 100
tensors

tensor([  1,   2, 100,   4])

In [25]:
arr # Sharing the same memory location

array([  1,   2, 100,   4])

In [26]:
# So, another way - using torch.tensor
tensor_arr = torch.tensor(arr)

In [28]:
tensor_arr

tensor([  1,   2, 100,   4])

In [30]:
tensor_arr[3] = 9
tensor_arr

tensor([  1,   2, 100,   9])

In [31]:
arr

array([  1,   2, 100,   4])

In [32]:
# zeros & ones
torch.zeros(2, 3, dtype = torch.float64)

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [33]:
torch.ones(2, 3, dtype = torch.float64)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [34]:
np.arange(0, 15).reshape(3, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [37]:
a = torch.tensor(np.arange(0, 15).reshape(3, 5))
print(a)

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])


In [38]:
a[:1]

tensor([[0, 1, 2, 3, 4]])

In [39]:
a[:, 0]

tensor([ 0,  5, 10])

In [41]:
a[:, 0:2]

tensor([[ 0,  1],
        [ 5,  6],
        [10, 11]])

In [42]:
a = torch.tensor([3, 4, 5], dtype = torch.float)
b = torch.tensor([6, 7, 8], dtype = torch.float)
print(a + b)

tensor([ 9., 11., 13.])


In [43]:
torch.add(a, b)

tensor([ 9., 11., 13.])

In [44]:
c = torch.add(a, b)
print(c)

tensor([ 9., 11., 13.])


In [45]:
c = torch.zeros(3)
torch.add(a, b, out = c)

tensor([ 9., 11., 13.])

In [46]:
c

tensor([ 9., 11., 13.])

In [47]:
torch.add(a, b).sum()

tensor(33.)

In [48]:
a.mul(b)

tensor([18., 28., 40.])

In [49]:
a.dot(b)

tensor(86.)

In [50]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype = torch.float)
y = torch.tensor([[1, 2], [4, 5], [7, 8]], dtype = torch.float)
x@y

tensor([[30., 36.],
        [66., 81.]])

In [51]:
x.mm(y)

tensor([[30., 36.],
        [66., 81.]])

In [53]:
torch.mm(x, y)

tensor([[30., 36.],
        [66., 81.]])

In [54]:
x.matmul(y)

tensor([[30., 36.],
        [66., 81.]])

In [55]:
torch.matmul(x, y)

tensor([[30., 36.],
        [66., 81.]])

In [61]:
d = torch.tensor(5.0, requires_grad = True)
e = d**2
e

tensor(25., grad_fn=<PowBackward0>)

In [62]:
# Backward Propagation
e.backward()

In [63]:
print(d.grad)

tensor(10.)


In [64]:
lst = [[1., 2., 3.], [5., 6., 7.], [4., 8., 9.]] # nested list
input_val = torch.tensor(lst, requires_grad = True)

In [65]:
print(input_val)

tensor([[1., 2., 3.],
        [5., 6., 7.],
        [4., 8., 9.]], requires_grad=True)


In [66]:
# y = x^3 + x^2
f = input_val**3 + input_val**2
f

tensor([[  2.,  12.,  36.],
        [150., 252., 392.],
        [ 80., 576., 810.]], grad_fn=<AddBackward0>)

In [68]:
g = f.sum()
g

tensor(2310., grad_fn=<SumBackward0>)

In [69]:
g.backward()

In [71]:
print(input_val.grad)

tensor([[  5.,  16.,  33.],
        [ 85., 120., 161.],
        [ 56., 208., 261.]])


In [76]:
h = f.clone().detach().requires_grad_(True)

In [77]:
h

tensor([[  2.,  12.,  36.],
        [150., 252., 392.],
        [ 80., 576., 810.]], requires_grad=True)

In [78]:
i = h.sum()

In [79]:
i

tensor(2310., grad_fn=<SumBackward0>)

In [80]:
i.backward()

In [81]:
print(h.grad)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
